# config/packages/twig.yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        site_name: 'Appart Hôtel Tricastin'
        site_phone: '+33 6 98 48 57 28'
        site_email: 'admin@appart-hotel-tricastin.com'
        site_address: '11 Boulevard Pont Achard, 26130 Saint paul les trois châteaux'

when@test:
    twig:
        strict_variables: true
