# config/services.yaml
parameters:
    contact_email: '%env(CONTACT_EMAIL)%'
    stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe.secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
   # ---- Cloudinary ----
    App\Service\CloudinaryService:
        arguments:
            $cloudinaryUrl: '%env(CLOUDINARY_URL)%'

    App\Twig\CloudinaryExtension:
        arguments:
            $cloudinaryUrl: '%env(CLOUDINARY_URL)%'

    App\Command\CloudinaryMigrateCommand:
        arguments:
            $projectDir: '%kernel.project_dir%'

    # ---- Mailer ----
    App\Service\MailerService:
        arguments:
            $appUrl: '%env(APP_URL)%'

    # ---- Stripe ----
    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
            $stripeWebhookSecret: '%env(STRIPE_WEBHOOK_SECRET)%'
            $appUrl: '%env(APP_URL)%'